image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: ignore

tasks:
  - name: Launch ngrok and port forward
    command: |
      bash /workspace/SMP-backup/port.sh

    openMode: tab-after

  - name: launch paper 
    command: |
      bash /workspace/SMP-backup/smp/launch.sh

    openMode: tab-after

  - name: Launch backup script
    command: |
      echo "starting backup script" && sleep 60 && bash /workspace/SMP-backup/smp/backup.sh

    openMode: tab-after

vscode:
  extensions:
    - ms-azuretools.vscode-docker

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
